spring:
  config:
    activate:
      # 当前配置名称
      on-profile: ext-json
  jackson:
    # 常规默认，枚举类 SerializationFeature 中的枚举属性为 key，值为 boolean 设置 jackson 序列化特性，具体 key 请看 SerializationFeature 源码
    serialization:
      # 忽略无法转换的对象
      fail-on-empty-beans: false
      # 是否使用缩进，格式化输出
      indent-output: false
      # 循环引用报错
      fail-on-self-references: true
      # 是否字符数组输出 json 数组 (false 则输出字符串)
      write-char-arrays-as-json-arrays: true
      # 循环引用返回 null
      write-self-references-as-null: false
      # 对象属性值是空集合是否输出空 json 数组
      write-empty-json-arrays: true
      # 是否将单个元素的集合展开，（即：去除数组符号"[]"）
      write-single-elem-arrays-unwrapped: false
      # map 序列化后，是否用 key 对其排序
      order-map-entries-by-keys: false
    # 枚举类 DeserializationFeature 中的枚举属性为 key，值为 boolean 设置 jackson 反序列化特性，具体 key 请看 DeserializationFeature 源码
    deserialization:
      # 允许对象忽略 json 中不存在的属性
      fail-on-unknown-properties: false
      # 将浮点数反序列化为 BIG-DECIMAL
      use-big-decimal-for-floats: true
    # 枚举类 MapperFeature 中的枚举属性为 key，值为 boolean 设置 jackson ObjectMapper 特性
    # ObjectMapper 在 jackson 中负责 json 的读写、json 与 pojo 的互转、json tree 的互转，具体特性请看 MapperFeature，常规默认即可
    mapper:
      # 使用 getter 取代 setter 探测属性，如类中含 getName() 但不包含 name 属性与 setName()，传输的 vo json 格式模板中依旧含 name 属性
      use-getters-as-setters: true