<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://maven.apache.org/POM/4.1.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.1.0 https://maven.apache.org/xsd/maven-4.1.0.xsd">
    <modelVersion>4.1.0</modelVersion>

    <groupId>ext.library</groupId>
    <artifactId>ext-parent</artifactId>
    <name>ext-parent</name>
    <version>${revision}</version>
    <packaging>pom</packaging>
    <description>Parent</description>
    <url>https://hygge.eu.org</url>


    <licenses>
        <license>
            <name>Apache License, Version 2.0</name>
            <url>https://www.apache.org/licenses/LICENSE-2.0</url>
        </license>
    </licenses>

    <properties>
        <!-- maven 配置 -->
        <java.version>25</java.version>
        <maven.compiler.release>${java.version}</maven.compiler.release>

        <!-- dependencies.version -->
        <revision>4.0.0</revision>
        <spring-boot.version>4.0.1</spring-boot.version>
        <mapstruct-plus.version>1.5.0</mapstruct-plus.version>
        <swagger.version>2.2.41</swagger.version>
        <mybatis-flex.version>1.11.4</mybatis-flex.version>
        <xbatis.version>1.9.5-M2-spring-boot4</xbatis.version>
        <bcprov.version>1.82</bcprov.version>
        <oshi.version>6.9.1</oshi.version>
        <springdoc.version>3.0.0</springdoc.version>
        <zxing-core.version>3.5.3</zxing-core.version>
        <guava.version>33.5.0-jre</guava.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <!-- ==================== 第三方 bom 导入 ================== -->
            <!-- 注意 bom 导入有优先级顺序，写在前面的优先级高 -->
            <!-- spring-boot -->
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-dependencies</artifactId>
                <version>${spring-boot.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <!-- mybatis-flex -->
            <dependency>
                <groupId>com.mybatis-flex</groupId>
                <artifactId>mybatis-flex-dependencies</artifactId>
                <version>${mybatis-flex.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>cn.xbatis</groupId>
                <artifactId>xbatis-spring-boot-parent</artifactId>
                <version>${xbatis.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <!-- ======================= 第三方依赖 ===================== -->
            <!-- mapstruct-plus -->
            <dependency>
                <groupId>io.github.linpeilie</groupId>
                <artifactId>mapstruct-plus-spring-boot-starter</artifactId>
                <version>${mapstruct-plus.version}</version>
            </dependency>
            <!-- guava -->
            <dependency>
                <groupId>com.google.guava</groupId>
                <artifactId>guava</artifactId>
                <version>${guava.version}</version>
            </dependency>
            <dependency>
                <groupId>org.bouncycastle</groupId>
                <artifactId>bcpkix-jdk18on</artifactId>
                <version>${bcprov.version}</version>
            </dependency>
            <!-- swagger-annotations -->
            <dependency>
                <groupId>io.swagger.core.v3</groupId>
                <artifactId>swagger-annotations</artifactId>
                <version>${swagger.version}</version>
            </dependency>
            <dependency>
                <groupId>com.github.therapi</groupId>
                <artifactId>therapi-runtime-javadoc</artifactId>
                <version>0.15.0</version>
            </dependency>
            <!-- oshi -->
            <dependency>
                <groupId>com.github.oshi</groupId>
                <artifactId>oshi-core-java25</artifactId>
                <version>${oshi.version}</version>
            </dependency>
            <!-- springdoc -->
            <dependency>
                <groupId>org.springdoc</groupId>
                <artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
                <version>${springdoc.version}</version>
            </dependency>
            <!-- google zxing -->
            <dependency>
                <groupId>com.google.zxing</groupId>
                <artifactId>javase</artifactId>
                <version>${zxing-core.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>

        <!-- 注解处理器 -->
        <dependency>
            <groupId>io.github.linpeilie</groupId>
            <artifactId>mapstruct-plus-processor</artifactId>
            <version>${mapstruct-plus.version}</version>
            <scope>provided</scope>
            <type>processor</type>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>com.github.therapi</groupId>
            <artifactId>therapi-runtime-javadoc-scribe</artifactId>
            <version>0.15.0</version>
            <scope>provided</scope>
            <type>processor</type>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-configuration-processor</artifactId>
            <version>${spring-boot.version}</version>
            <scope>provided</scope>
            <type>processor</type>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-autoconfigure-processor</artifactId>
            <version>${spring-boot.version}</version>
            <scope>provided</scope>
            <type>processor</type>
            <optional>true</optional>
        </dependency>
    </dependencies>

    <build>
        <pluginManagement>
            <plugins>
                <!-- 编译插件 -->
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <configuration>
                        <parameters>true</parameters>
                    </configuration>
                </plugin>
                <!-- 源文件打包 -->
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-source-plugin</artifactId>
                    <executions>
                        <execution>
                            <id>attach-sources</id>
                            <phase>package</phase>
                            <goals>
                                <goal>jar-no-fork</goal>
                            </goals>
                        </execution>
                    </executions>
                </plugin>
            </plugins>
        </pluginManagement>
    </build>

</project>
