spring:
  profiles:
    include: ext
  application:
    name: demo-web
  datasource:
    username: root
    url: jdbc:mysql://127.0.0.1:3306/demo?zeroDateTimeBehavior=CONVERT_TO_NULL&rewriteBatchedStatements=true
  data:
    redis:
      host: 127.0.0.1
  web:
    resources:
      add-mappings: true
      static-locations[0]: classpath:/public/**
  mvc:
    # 404 抛异常
    static-path-pattern: /static/**
server:
  servlet:
    context-path: /ext
ext:
  captcha:
    captcha-type: MATH
  web:
    invoke-time-enabled: true
  mybatis:
    sql-print: true
  security:
    enable-cookie: true
    repository: redis
mybatis-flex:
  global-config:
    print-banner: false
