<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.1.0 https://maven.apache.org/xsd/maven-4.1.0.xsd">
    <modelVersion>4.1.0</modelVersion>

    <groupId>ext.library</groupId>
    <artifactId>ext-pom</artifactId>
    <version>${revision}</version>
    <packaging>bom</packaging>
    <name>ext-pom</name>
    <description>Ext Library BOM - 依赖版本管理</description>

    <properties>
        <revision>4.0.0</revision>
    </properties>

    <dependencyManagement>
        <dependencies>
            <!-- ======================= Ext 模块 ===================== -->
            <dependency>
                <groupId>ext.library</groupId>
                <artifactId>ext-tool</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>ext.library</groupId>
                <artifactId>ext-core</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>ext.library</groupId>
                <artifactId>ext-json</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>ext.library</groupId>
                <artifactId>ext-redis</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>ext.library</groupId>
                <artifactId>ext-cache</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>ext.library</groupId>
                <artifactId>ext-mail</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>ext.library</groupId>
                <artifactId>ext-security</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>ext.library</groupId>
                <artifactId>ext-crypto</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>ext.library</groupId>
                <artifactId>ext-mvc</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>ext.library</groupId>
                <artifactId>ext-openapi</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>ext.library</groupId>
                <artifactId>ext-sse</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>ext.library</groupId>
                <artifactId>ext-websocket</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>ext.library</groupId>
                <artifactId>ext-captcha</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>ext.library</groupId>
                <artifactId>ext-idempotent</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>ext.library</groupId>
                <artifactId>ext-desensitize</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>ext.library</groupId>
                <artifactId>ext-trans</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>ext.library</groupId>
                <artifactId>ext-api-crypto</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>ext.library</groupId>
                <artifactId>ext-http</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>ext.library</groupId>
                <artifactId>ext-qrcode</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>ext.library</groupId>
                <artifactId>ext-monitor</artifactId>
                <version>${revision}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

</project>
